# -*- coding: utf-8 -*-

items = [
         # Pricing   
         ['a','Ask'],
         ['b','Bid'],
         ['p','Previous Close'],
         ['o','Open'],
         # Dividends
         ['y','Dividend Yield'],         
         ['d','Dividend/Share'],
         ['r1','Dividend Pay Date'],
         ['q','Ex-Dividend Date'],
         # Date
         ['c1','Change'],         
         ['c','Change and Percentage Change'],
         ['k2','Change Percent'],
         ['p2','Change in Percent'],
         ['d1','Last Trade Date'],
         ['d2','Trade Date'],
         ['t1','Last Trade Time'],
         # Averages
         ['c8','After Hours Change'],         
         ['c3','Commission'],
         ['g',"Day's Low"],
         ['h',"Day's High"],
         ['l','Last Trade (with time)'],
         ['l1','Last Trade (price only)'],          
         ['t8','1 yr Target Price'],          
         ['m3','50 Day Moving Avg'],
         ['m4','200 Day Moving Avg'],
         ['m5','Change from 200 Day Moving Avg'],
         ['m6',' Percentage Change from 200 Day Moving Avg'],
         ['m7','Change from 50 Day Moving Avg'],
         ['m8','Percentage Change from 50 Day Moving Avg'],
         # Misc
         ['w1',"Day's Value Change"],         
         ['p1','Price Paid'],
         ['m',"Day's Range"],         
         ['g1','Holding Gain Percent'],         
         ['g3','Annualized Gain'],         
         ['g4','Holdings Gain'],         
         ['t7','Ticker Trend'],         
         ['t6','Trade Links'],         
         ['l2','High Limit'],         
         ['l3','Low Limit'],         
         ['v1','Holdings Value'],
         ['s6','Revenue'],
         # 52 Week Pricing
         ['k','52 Week High'],         
         ['j','52 Week Low'],
         ['j5','Change from 52 Week Low'],
         ['k4','Change from 52 Week High'],
         ['j6','Percentage Change from 52 Week Low'],
         ['k5','Percentage Change from 52 Week High'],
         ['w','52 Week Range'], 
         # Symbol Info
         ['v','More Info'],          
         ['j1','Market Capitalization'], 
         ['f6','Float Shares'], 
         ['n','Name'], 
         ['n4','Notes'], 
         ['s','Symbol'], 
         ['s1','Shares Owned'], 
         ['x','Stock Exchange'], 
         ['j2','Shares Outstanding'], 
         # Volume
         ['v','Volume'],          
         ['a5','Ask Size'], 
         ['b6','Bid Size'], 
         ['k3','Last Trade Size'], 
         ['a2','Avg Daily Volume'], 
         # Ratios
         ['e','Earnings/Share'],          
         ['e7','EPS Estimate Current Year'],
         ['e8','EPS Estimate Next Year'],
         ['e9','EPS Estimate Next Quarter'],
         ['b4','Book Value'],
         ['j4','EBITDA'],
         ['p5','Price/Shares'],
         ['p6','Price/Book'],
         ['r','P/E Ratio'],
         ['r5','PEG Ratio'],
         ['r6','Price/EPS Estimate Current Year'],
         ['r7','Price/EPS Estimate Next Year'],
         ['s7','Short Ratio']
        ]

# The following tags are not standard 

items_key_stat = {
                   # Valuation Measures
                   'vm1': 'Market Cap (intraday)',
                   'vm2': 'Enterprise Value',
                   'vm3': 'Trailing P/E',
                   'vm4': 'Forward P/E',
                   'vm5': 'PEG Ratio (5 yr expected)',
                   'vm6': 'Price/Sales',
                   'vm7': 'Price/Book',
                   'vm8': 'Enterprise Value/Revenue',
                   'vm9': 'Enterprise Value/EBITDA',
                   # Fiscal Year
                   'fy1': 'Fiscal Year Ends',
                   'fy2': 'Most Recent Quarter',
                   # Profitability
                   'pf1': 'Profit Margin',
                   'pf2': 'Operating Margin',
                   # Management Effectiveness
                   'me1': 'Return on Assets',
                   'me2': 'Return on Equity',
                   # Income Statement
                   'is1': 'Revenue',
                   'is2': 'Revenue Per Share',
                   'is3': 'Quarterly Revenue Growth',
                   'is4': 'Gross Profit',
                   'is5': 'EBITDA',
                   'is6': 'Net Income Avi to Common',
                   'is7': 'Diluted EPS',
                   'is8': 'Quarterly Earnings Growth',
                   # Balance Sheet
                   'bs1': 'Total Cash',
                   'bs2': 'Total Cash Per Share',
                   'bs3': 'Total Debt',
                   'bs4': 'Total Debt/Equity',
                   'bs5': 'Current Ratio',
                   'bs6': 'Book Value Per Share',
                   # Cash Flow Statement
                   'cf1': 'Operating Cash Flow',
                   'cf2': 'Levered Free Cash Flow',
                   # Stock Price History
                   'ph1': 'Beta',
                   'ph2': '52-Week Change',
                   'ph3': 'S&P500 52-Week Change',
                   'ph4': '52 Week High',
                   'ph5': '52 Week Low',
                   'ph6': '50-Day Moving Average',
                   'ph7': '200-Day Moving Average',
                   # Share Statistics
                   'ss1': 'Avg Vol (3 month)',
                   'ss2': 'Avg Vol (10 day)',
                   'ss3': 'Shares Outstanding', 
                   'ss4': 'Float',
                   'ss5': '% Held by Insiders',
                   'ss6': '% Held by Institutions',
                   'ss7': 'Shares Short',
                   'ss8': 'Short Ratio',
                   'ss9': 'Short % of Float',
                   'ss10': 'Shares Short (prior month)',
                   # Dividends & Splits
                   'ds1': 'Forward Annual Dividend Rate',
                   'ds2': 'Forward Annual Dividend Yield',
                   'ds3': 'Trailing Annual Dividend Rate',
                   'ds4': 'Trailing Annual Dividend Yield',
                   'ds5': '5 Year Average Dividend Yield',
                   'ds6': 'Payout Ratio',
                   'ds7': 'Dividend Date',
                   'ds8': 'Ex-Dividend Date',
                   'ds9': 'Last Split Factor (new per old)',
                   'ds10': 'Last Split Date'
                 }